version: '3'
services: 
    libsnark:
        image: xiabee/libsnark
        build: ./libsnark
        volumes: 
            - ./src:/app/lib/src
        environment: 
            TZ: Asia/Shanghai
        # restart: always
        stdin_open: true # -i interactive
        tty: true # -t tty
        privileged: true
        entrypoint: ["sh"] # sh
        networks:
            - default